# Generated by Django 5.1.1 on 2024-09-24 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
